# This workflow will build and deploy a Node.js project to GitHub Pages.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04 # stick to LTS

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Using LTS

      - name: Install dependencies in docs folder
        run: npm ci
        working-directory: ./docs

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact from docs folder
        uses: actions/upload-pages-artifact@v3
        with:
          # Uploading the contents of the 'docs' folder directly
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

